/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shippment.Consolidate1;

import java.util.LinkedList;
import java.util.List;

import org.junit.Test;

import shippment.Consolidate1.service.ConsolidateService;

public class ConsolidateServiceTest {
	
	List<int[]> zipcodeList = new LinkedList<int[]>();
	
    @Test public void testSomeLibraryMethod() {
    	ConsolidateService consolidateService = new ConsolidateService();
    	zipcodesList();
    	consolidateService.runZipcodeConsodilation(zipcodeList);
    	
    }
    
    private void zipcodesList(){
    	
    	//change your zipcodes here and modify the corresponding list below and run the Junit.
    	int [] arry1 = new int[]{49679,52015};
		int [] arry2 = new int[]{49800,50000};
		int [] arry3 = new int[]{51500,53479};
		int [] arry4 = new int[]{45012,46937};
		int [] arry5 = new int[]{54012,59607};
		int [] arry6 = new int[]{45500,45590};
		int [] arry7 = new int[]{45999,47900};
		int [] arry8 = new int[]{44000,45000};
		int [] arry9 = new int[]{43012,45950};		
		zipcodeList.add(arry1);
		zipcodeList.add(arry2);
		zipcodeList.add(arry3);
		zipcodeList.add(arry4);
		zipcodeList.add(arry5);
		zipcodeList.add(arry6);
		zipcodeList.add(arry7);
		zipcodeList.add(arry8);
		zipcodeList.add(arry9);
    }
}
